ListaPessoas/src/java/br/upf/pos/listapessoas/mbeans/ListaPessoasMB.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.upf.pos.listapessoas.mbeans;

import br.upf.pos.listapessoas.modelo.Pessoa;
import br.upf.pos.listapessoas.sgbeans.ListaPessoasBean;
import java.util.ArrayList;
import java.util.List;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;

/**
 *
 * @author Felipe
 */
@ManagedBean
@RequestScoped
public class ListaPessoasMB {

    @EJB
    private ListaPessoasBean listaPessoasBean;
    private String nome;
    private Integer idade;
    
    /**
     * Creates a new instance of ListaPessoasMB
     */
    public ListaPessoasMB() {
    }
    
    public List<Pessoa> getPessoas() {
        return new ArrayList<>(listaPessoasBean.getPessoas());
    }
    
    public void adiciona() {
        listaPessoasBean.adiciona(nome, idade);
    }
    
    public void remove(Pessoa pessoa) {
        listaPessoasBean.remove(pessoa);
    }
    
    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public Integer getIdade() {
        return idade;
    }

    public void setIdade(Integer idade) {
        this.idade = idade;
    }

    public int getQtdCriancas() {
        return listaPessoasBean.getCrianca();
    }

    public int getQtdAdolecentes() {
        return listaPessoasBean.getAdolecente();
    }

    public int getQtdAdultos() {
        return listaPessoasBean.getAdulto();
    } 
    
    
    
}

ListaPessoas/src/java/br/upf/pos/listapessoas/sgbeans/ListaPessoasBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.upf.pos.listapessoas.sgbeans;

import br.upf.pos.listapessoas.modelo.Pessoa;
import java.util.HashSet;
import java.util.Set;
import javax.ejb.Singleton;

/**
 *
 * @author Felipe
 */
@Singleton
public class ListaPessoasBean {
    private final Set<Pessoa> pessoas = new HashSet<>();
    private Integer crianca=0, adolecente=0, adulto=0;
    
    public void adiciona(String nome, Integer idade) {
        Pessoa pessoa = new Pessoa();
        pessoa.setNome(nome);
        pessoa.setIdade(idade);
        pessoas.add(pessoa);
        
        if(idade<13) {
            crianca++;
        }
        else if(idade >=13 && idade <= 19) {
            adolecente++;
        }
        else if(idade >19) {
            adulto++;
        }
        
    }
    
    public void remove(Pessoa pessoa) {
        
        if(pessoa.getIdade()<13) {
            crianca--;
        }
        else if(pessoa.getIdade() >=13 && pessoa.getIdade() <= 19) {
            adolecente--;
        }
        else if(pessoa.getIdade() >19) {
            adulto--;
        }
        
        pessoas.remove(pessoa);
    }
    
    public Set<Pessoa> getPessoas() {
        return pessoas;
    }

    public Integer getCrianca() {
        return crianca;
    }

    public Integer getAdolecente() {
        return adolecente;
    }

    public Integer getAdulto() {
        return adulto;
    }   
}

ListaPessoas/web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>pessoas</title>
    </h:head>
    <h:body>
        <h:form>
            <h:outputLabel value="Nome: "/>
            <h:inputText value="#{listaPessoasMB.nome}"/>
            
            <h:outputLabel value="Idade: "/>
            <h:inputText value="#{listaPessoasMB.idade}"/>
            
            <h:commandButton action="#{listaPessoasMB.adiciona()}" value="Adiciona pessoa"/>
            <hr/>
            <h:outputLabel value="Pessoas:"/>
            <h:dataTable value="#{listaPessoasMB.pessoas}" var="p">
                <h:column>
                    <h:outputText value="#{p.nome}"/>
                </h:column>
                <h:column>
                    <h:outputText value="#{p.idade}"/>
                </h:column>
                <h:column>
                    <h:commandLink action="#{listaPessoasMB.remove(p)}" value="Remover"/>
                </h:column>
            </h:dataTable>
            <hr/>
            
            <h:outputLabel value="Quantidade crianças: #{listaPessoasMB.qtdCriancas} adolecentes: #{listaPessoasMB.qtdAdolecentes} adultos: #{listaPessoasMB.qtdAdultos}"/>
            
            
        </h:form>
    </h:body>
</html>