EstacoesView/src/java/mbeans/LoginMB.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mbeans;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

/**
 *
 * @author Filipe
 */
@ManagedBean
@SessionScoped
public class LoginMB {
    private String usr;
    private String pwd;

    public LoginMB() {
    }
    
    public String valida(){
        if (usr.equals("pos") && (pwd.equals("pos"))){
            return "bemvindo?faces-redirect=true";
        } else {
            return "errologin?faces-redirect=true";
        }
    }

    public String getUsr() {
        return usr;
    }

    public void setUsr(String usr) {
        this.usr = usr;
    }

    public String getPwd() {
        return pwd;
    }

    public void setPwd(String pwd) {
        this.pwd = pwd;
    }
    
    
    
}

EstacoesView/src/java/uteis/EstadoController.java
package uteis;

import br.upf.estacoes.model.beans.Estado;
import uteis.util.JsfUtil;
import uteis.util.PaginationHelper;
import sbeans.EstadoFacade;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("estadoController")
@SessionScoped
public class EstadoController implements Serializable {

    private Estado current;
    private DataModel items = null;
    @EJB
    private sbeans.EstadoFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public EstadoController() {
    }

    public Estado getSelected() {
        if (current == null) {
            current = new Estado();
            selectedItemIndex = -1;
        }
        return current;
    }

    private EstadoFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Estado) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Estado();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("EstadoCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Estado) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("EstadoUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Estado) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("EstadoDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Estado getEstado(java.lang.Integer id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Estado.class)
    public static class EstadoControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            EstadoController controller = (EstadoController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "estadoController");
            return controller.getEstado(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Estado) {
                Estado o = (Estado) object;
                return getStringKey(o.getId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Estado.class.getName());
            }
        }

    }

}

EstacoesView/web/bemvindo.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                template="./modeloTLCB.xhtml">

    <ui:define name="title">
        Bem Vindo
    </ui:define>

    <ui:define name="top">
        Topo
    </ui:define>

    <ui:define name="left">
        Menu
    </ui:define>

    <ui:define name="content">
        Seja bem-vindo ao sistema, #{loginMB.usr}.
    </ui:define>

    <ui:define name="bottom">
        Hoje é...
    </ui:define>

</ui:composition>

EstacoesView/web/errologin.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                template="./modeloTLCB.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html">

    <ui:define name="title">
        Erro - Login inválido
    </ui:define>

    <ui:define name="top">
        Topo
    </ui:define>

    <ui:define name="left">
        Menu...
    </ui:define>

    <ui:define name="content">
        Erro ao entrar no sistema. Clique <h:form><h:commandLink value="aqui" action="login.xhtml"/></h:form> para tentar novamente.
         
    </ui:define>

    <ui:define name="bottom">
        Hoje é...
    </ui:define>

</ui:composition>

EstacoesView/web/estado/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateEstadoTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateEstadoLabel_versao}" for="versao"/>
                    <h:inputText readonly="true" id="versao" value="#{estadoController.selected.versao}" title="#{bundle.CreateEstadoTitle_versao}" />
                    <h:outputLabel value="#{bundle.CreateEstadoLabel_id}" for="id" />
                    <h:inputText readonly="true" id="id" value="#{estadoController.selected.id}" title="#{bundle.CreateEstadoTitle_id}" />
                    <h:outputLabel value="#{bundle.CreateEstadoLabel_nome}" for="nome" />
                    <h:inputText id="nome" value="#{estadoController.selected.nome}" title="#{bundle.CreateEstadoTitle_nome}" />
                    <h:outputLabel value="#{bundle.CreateEstadoLabel_sigla}" for="sigla" />
                    <h:inputText id="sigla" value="#{estadoController.selected.sigla}" title="#{bundle.CreateEstadoTitle_sigla}" />
                </h:panelGrid>
                <br />
                <h:commandLink action="#{estadoController.create}" value="#{bundle.CreateEstadoSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{estadoController.prepareList}" value="#{bundle.CreateEstadoShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateEstadoIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

EstacoesView/web/estado/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditEstadoTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditEstadoLabel_versao}" for="versao" />
                    <h:inputText readonly="true" id="versao" value="#{estadoController.selected.versao}" title="#{bundle.EditEstadoTitle_versao}" />
                    <h:outputLabel value="#{bundle.EditEstadoLabel_id}" for="id" />
                    <h:inputText readonly="true" id="id" value="#{estadoController.selected.id}" title="#{bundle.EditEstadoTitle_id}" />
                    <h:outputLabel value="#{bundle.EditEstadoLabel_nome}" for="nome" />
                    <h:inputText id="nome" value="#{estadoController.selected.nome}" title="#{bundle.EditEstadoTitle_nome}" />
                    <h:outputLabel value="#{bundle.EditEstadoLabel_sigla}" for="sigla" />
                    <h:inputText id="sigla" value="#{estadoController.selected.sigla}" title="#{bundle.EditEstadoTitle_sigla}" />
                </h:panelGrid>
                <h:commandLink action="#{estadoController.update}" value="#{bundle.EditEstadoSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditEstadoViewLink}"/>
                <br />
                <h:commandLink action="#{estadoController.prepareList}" value="#{bundle.EditEstadoShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditEstadoIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

EstacoesView/web/estado/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListEstadoTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListEstadoEmpty}" rendered="#{estadoController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{estadoController.items.rowCount > 0}">
                    <h:outputText value="#{estadoController.pagination.pageFirstItem + 1}..#{estadoController.pagination.pageLastItem + 1}/#{estadoController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{estadoController.previous}" value="#{bundle.Previous} #{estadoController.pagination.pageSize}" rendered="#{estadoController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{estadoController.next}" value="#{bundle.Next} #{estadoController.pagination.pageSize}" rendered="#{estadoController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{estadoController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListEstadoTitle_versao}"/>
                            </f:facet>
                            <h:outputText value="#{item.versao}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListEstadoTitle_id}"/>
                            </f:facet>
                            <h:outputText value="#{item.id}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListEstadoTitle_nome}"/>
                            </f:facet>
                            <h:outputText value="#{item.nome}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListEstadoTitle_sigla}"/>
                            </f:facet>
                            <h:outputText value="#{item.sigla}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{estadoController.prepareView}" value="#{bundle.ListEstadoViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{estadoController.prepareEdit}" value="#{bundle.ListEstadoEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{estadoController.destroy}" value="#{bundle.ListEstadoDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{estadoController.prepareCreate}" value="#{bundle.ListEstadoCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListEstadoIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

EstacoesView/web/estado/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewEstadoTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewEstadoLabel_versao}"/>
                    <h:outputText value="#{estadoController.selected.versao}" title="#{bundle.ViewEstadoTitle_versao}"/>
                    <h:outputText value="#{bundle.ViewEstadoLabel_id}"/>
                    <h:outputText value="#{estadoController.selected.id}" title="#{bundle.ViewEstadoTitle_id}"/>
                    <h:outputText value="#{bundle.ViewEstadoLabel_nome}"/>
                    <h:outputText value="#{estadoController.selected.nome}" title="#{bundle.ViewEstadoTitle_nome}"/>
                    <h:outputText value="#{bundle.ViewEstadoLabel_sigla}"/>
                    <h:outputText value="#{estadoController.selected.sigla}" title="#{bundle.ViewEstadoTitle_sigla}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{estadoController.destroyAndView}" value="#{bundle.ViewEstadoDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewEstadoEditLink}"/>
                <br />
                <h:commandLink action="#{estadoController.prepareCreate}" value="#{bundle.ViewEstadoCreateLink}" />
                <br />
                <h:commandLink action="#{estadoController.prepareList}" value="#{bundle.ViewEstadoShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewEstadoIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>

EstacoesView/web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Facelet Title</title>
        <h:outputStylesheet name="css/jsfcrud.css"/>
    </h:head>
    <h:body>
        Hello from Facelets
        <br />
        <h:link outcome="/estado/List" value="Show All Estado Items"/>
    </h:body>

</html>

EstacoesView/web/login.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                template="./modeloTLCB.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html">

    <ui:define name="title">
        Login Obrigatório
    </ui:define>

    <ui:define name="top">
        Login - Sistema de Manutenção de Estações
    </ui:define>

    <ui:define name="content">
        <h:form>
            <h:outputLabel value="Usuário:"/><h:inputText value="#{loginMB.usr}"/><br/>
            <h:outputLabel value="Senha:"/><h:inputSecret value="#{loginMB.pwd}"/><br/>
            <h:commandButton value="Valida" action="#{loginMB.valida()}"/> 
        </h:form>
    </ui:define>

</ui:composition>

EstacoesView/web/modeloTC.xhtml
<?xml version='1.0' encoding='UTF-8' ?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html">

    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <h:outputStylesheet name="./css/default.css"/>
        <h:outputStylesheet name="./css/cssLayout.css"/>
        <title> <ui:insert name="title">Title</ui:insert></title>
    </h:head>

    <h:body>

        <div id="top" class="top">
            <ui:insert name="top">Top</ui:insert>
        </div>

        <div id="content" class="center_content">
            <ui:insert name="content">Content</ui:insert>
        </div>

    </h:body>

</html>

EstacoesView/web/modeloTCB.xhtml
<?xml version='1.0' encoding='UTF-8' ?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html">

    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <h:outputStylesheet name="./css/default.css"/>
        <h:outputStylesheet name="./css/cssLayout.css"/>
        <title><ui:insert name="title">Title</ui:insert></title>
    </h:head>

    <h:body>

        <div id="top">
            <ui:insert name="top">Top</ui:insert>
        </div>

        <div id="content" class="center_content">
            <ui:insert name="content">Content</ui:insert>
        </div>

        <div id="bottom">
            <ui:insert name="bottom">Bottom</ui:insert>
        </div>

    </h:body>

</html>

EstacoesView/web/modeloTLCB.xhtml
<?xml version='1.0' encoding='UTF-8' ?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html">

    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <h:outputStylesheet name="./css/default.css"/>
        <h:outputStylesheet name="./css/cssLayout.css"/>
        <title><ui:insert name="title">Title</ui:insert></title>
    </h:head>

    <h:body>

        <div id="top">
            <ui:insert name="top">Top</ui:insert>
        </div>
        <div>
            <div id="left">
                <ui:insert name="left">Left</ui:insert>
            </div>
            <div id="content" class="left_content">
                <ui:insert name="content">Content</ui:insert>
            </div>
        </div>
        <div id="bottom">
            <ui:insert name="bottom">Bottom</ui:insert>
        </div>

    </h:body>

</html>

EstacoesView/web/template.xhtml
<?xml version='1.0' encoding='UTF-8' ?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title><ui:insert name="title">Default Title</ui:insert></title>
<h:outputStylesheet name="css/jsfcrud.css"/>
    </h:head>

    <h:body>
        <h1>
            <ui:insert name="title">Default Title</ui:insert>
        </h1>
        <p>
            <ui:insert name="body">Default Body</ui:insert>
        </p>
    </h:body>

</html>